# Tokenization

In [1]:
# tokenization
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
tokenizer = Tokenizer(num_words=15, oov_token="-")

In [3]:
# text to tokenized
teks = ["Saya Suka Programming",
        "Programming sangat menyenangkan",
        "Machine Learning berbeda dengan pemrograman konvensional",
        "Axel jatuh cinta sama Meltryllis"]

In [4]:
# implement tokenization
tokenizer.fit_on_texts(teks)

In [5]:
# change text into sequence
sequences = tokenizer.texts_to_sequences(teks)

In [6]:
# print tokenized word
print(tokenizer.word_index)

{'-': 1, 'programming': 2, 'saya': 3, 'suka': 4, 'sangat': 5, 'menyenangkan': 6, 'machine': 7, 'learning': 8, 'berbeda': 9, 'dengan': 10, 'pemrograman': 11, 'konvensional': 12, 'axel': 13, 'jatuh': 14, 'cinta': 15, 'sama': 16, 'meltryllis': 17}


In [10]:
print(tokenizer.texts_to_sequences(['Saya Suka Programming']))
print(tokenizer.texts_to_sequences(['Saya suka belajar programing sejak smp']))

[[3, 4, 2]]
[[3, 4, 1, 1, 1, 1]]


In [15]:
# padding on text
from tensorflow.keras.preprocessing.sequence import pad_sequences
sequences_samapanjang = pad_sequences(sequences,
                                      padding='post', #add padding in the end of text
                                      maxlen=5, # max sequence length
                                      truncating='post') #take the first maxlen words and discard the rest if words > maxlen
print(sequences_samapanjang)

[[ 3  4  2  0  0]
 [ 2  5  6  0  0]
 [ 7  8  9 10 11]
 [13 14  1  1  1]]


# Embedding

In [ ]:
# embedding
model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(jumlah_kata, dimensi_embedding, panjang_input),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.fit(padded_latih, label_latih,
          epochs=num_epochs,
          validation_data=(padded_test, label_test))